name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: npm run lint
    - name: Run Tests
      run: npm test
